---
- hosts: all
  vars:
    administrator_name: corpadmin
    administrator_password: $6$mysecretsalt$KoHdLUz/CewFYnXO.t8Ik74qVxb/yj3Dk2J4Ff4lgG9lB/kXx6JCQbd8f3GtHev1IrAN2c6rzCQrZ0AGRi7Hk1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Update software packages
      yum: name=* state=latest
    - name: Create user
      user: name={{administrator_name}} password={{administrator_password}}
- hosts: web1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Install NgInx
      yum: name=nginx state=latest
    - name: Copy default.conf.j2 to the system directory
      template:
        src: ./default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        force: yes
    - name: Start NgInx on boot
      service: name=nginx state=started enabled=yes
- hosts: database1
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Install mysql server package
      yum: name=mysql-server state=latest
    - name: Start mysql server on boot
      service: name=mysqld state=started enabled=yes
    - name: create directories
      file: dest=/var/data/client{{item}} state=directory
      with_sequence: start=1 end=5
